#!/bin/sh

# Get list of staged files excluding deleted files (lowercase d in --diff-filter).
FILES=$(git diff --cached --name-only --diff-filter=d | grep \\.php)
if [[ $(echo $FILES | wc -c) -eq "1" ]]
then
  # No files staged, let git handle the rest.
  exit 0
fi

GREEN=''
LRED=''
NC=''

# Check if colors are supported.
if [[ $(tput colors) -gt "2" ]]
then
  GREEN='\033[0;32m'
  LRED='\033[1;31m'
  NC='\033[0m'
fi

# Use local or global phpcs. Local has the priority.
GIT_DIR=$(git rev-parse --show-toplevel)
PHPCS="phpcs"
if [ -f "$GIT_DIR/vendor/bin/phpcs" ]; then
  PHPCS="$GIT_DIR/vendor/bin/phpcs"
fi

# Generate diff file from phpcs.
echo ${GREEN}Creating patch for staged files\(can take some time\).${NC}
$PHPCS -p --report-diff=phpcspatch.diff $FILES

# Check if there is anything to patch.
WORDS=$( cat phpcspatch.diff | wc -m )
if [[ "$WORDS" -gt "1" ]]
then
  # Apply diff file.
  echo ${GREEN}Patching staged files.${NC}
  patch -p0 -ui phpcspatch.diff

  # Remove the diff file.
  echo ${GREEN}Removing patch file.${NC}
  rm phpcspatch.diff

  echo ${LRED}Please stage the new changes.${NC}

  exit 1
else
  # Nothing to patch so git can commit as normal.
  echo ${GREEN}Nothing to patch.${NC}
  rm phpcspatch.diff
  exit 0
fi